DEFAULT_PERMISSIONS = [
    {"_id": "users:read", "name": "View Users"},
    {"_id": "users:create", "name": "Create Users"},
    {"_id": "users:update", "name": "Edit Users"},
    {"_id": "users:delete", "name": "Delete Users"},
    {"_id": "roles:read", "name": "View Roles"},
    {"_id": "roles:create", "name": "Create Roles"},
    {"_id": "roles:update", "name": "Edit Roles"},
    {"_id": "roles:delete", "name": "Delete Roles"},
    {"_id": "permissions:read", "name": "Read Permissions"},
    {"_id": "documents:read", "name": "View Documents"},
    {"_id": "documents:create", "name": "Draft Documents"},
    {"_id": "documents:update", "name": "Edit Documents"},
    {"_id": "documents:delete", "name": "Delete Documents"},
    {"_id": "documents:approve", "name": "Approve Documents"},
    {"_id": "documents:share", "name": "Share Documents"},
    {"_id": "documents:upload", "name": "Upload Documents"},
    {"_id": "documents:download_all", "name": "Download Complete Project Documents"},
    {"_id": "documents:comment", "name": "Add Inputs/Comments"},
    {"_id": "tags:read", "name": "View Tags"},
    {"_id": "tags:create", "name": "Create Tags"},
    {"_id": "tags:update", "name": "Edit Tags"},
    {"_id": "tags:delete", "name": "Delete Tags"},
    {"_id": "projects:read", "name": "View Projects"},
    {"_id": "projects:create", "name": "Create Projects"},
    {"_id": "projects:update", "name": "Edit Projects"},
    {"_id": "projects:delete", "name": "Delete Projects"},
    {"_id": "projects:assign", "name": "Assign Members"},
    {"_id": "organizations:read", "name": "View Organizations"},
    {"_id": "organizations:create", "name": "Create Organizations"},
    {"_id": "organizations:update", "name": "Edit Organizations"},
    {"_id": "organizations:delete", "name": "Delete Organizations"},
    {"_id": "parties:read", "name": "View Parties"},
    {"_id": "parties:create", "name": "Create Parties"},
    {"_id": "parties:update", "name": "Edit Parties"},
    {"_id": "parties:delete", "name": "Delete Parties"},
    {"_id": "representatives:read", "name": "View Representatives"},
    {"_id": "representatives:create", "name": "Create Representatives"},
    {"_id": "representatives:update", "name": "Edit Representatives"},
    {"_id": "representatives:delete", "name": "Delete Representatives"},
    {"_id": "concerns:read", "name": "View Concerns"},
        {"_id": "concerns:create", "name": "Create Concerns"},
        {"_id": "concerns:update", "name": "Edit Concerns"},
    {"_id": "concerns:delete", "name": "Delete Concerns"},
    {"_id": "reports:view", "name": "View Reports"},
    {"_id": "reports:create", "name": "Create Reports"},
    {"_id": "settings:view", "name": "View Settings"},
    {"_id": "settings:edit", "name": "Edit Settings"},
    {"_id": "email_groups:read", "name": "View Email Groups"},
    {"_id": "email_groups:create", "name": "Create Email Groups"},
    {"_id": "email_groups:update", "name": "Edit Email Groups"},
    {"_id": "email_groups:delete", "name": "Delete Email Groups"},
    {"_id": "input_requests:read", "name": "View Input Requests"},
    {"_id": "input_requests:create", "name": "Create Input Requests"},
    {"_id": "input_requests:update", "name": "Edit Input Requests"},
    {"_id": "input_requests:respond", "name": "Respond to Input Requests"},
    {"_id": "input_requests:admin", "name": "Administer Input Requests"},
    {"_id": "performance:admin", "name": "Performance Admin"},
    {"_id": "performance:superadmin", "name": "Performance Superadmin"},
    {"_id": "users:lock", "name": "Lock Users"},
    {"_id": "users:unlock", "name": "Unlock Users"},
    {"_id": "dms.document.view", "name": "View DMS Documents"},
    {"_id": "dms.document.upload", "name": "Upload DMS Documents"},
    {"_id": "dms.document.edit_metadata", "name": "Edit DMS Document Metadata"},
    {"_id": "dms.document.delete", "name": "Delete DMS Documents"},
    {"_id": "dms.document.download", "name": "Download DMS Documents"},
    {"_id": "dms.document.bulk_download", "name": "Bulk Download DMS Documents"},
    {"_id": "dms.document.link_reference", "name": "Link DMS Document References"},
    {"_id": "dms.status.update", "name": "Update DMS Status"},
    {"_id": "dms.comment.add", "name": "Add DMS Comments"},
    {"_id": "dms.dashboard.view", "name": "View DMS Dashboard"},
    {"_id": "dms.report.view", "name": "View DMS Reports"},
    {"_id": "dms.user.manage", "name": "Manage Client DMS Users"},
    {"_id": "dms.project.manage", "name": "Manage Client DMS Projects"},
    {"_id": "dms.audit.view", "name": "View DMS Audit Trail"},
    {"_id": "dms.admin", "name": "Administer Client DMS"},
    {"_id": "drafting.request.view", "name": "View Drafting Requests"},
    {"_id": "drafting.request.create", "name": "Create Drafting Requests"},
    {"_id": "drafting.request.accept", "name": "Accept Drafting Requests"},
    {"_id": "drafting.request.assign", "name": "Assign Drafting Work"},
    {"_id": "drafting.draft.create", "name": "Create Expert Drafts"},
    {"_id": "drafting.draft.edit", "name": "Edit Expert Drafts"},
    {"_id": "drafting.draft.submit_for_review", "name": "Submit Drafts for Review"},
    {"_id": "drafting.review.perform", "name": "Perform Expert Review"},
    {"_id": "drafting.review.approve", "name": "Approve Expert Review"},
    {"_id": "drafting.review.return_for_revision", "name": "Return Draft for Revision"},
    {"_id": "drafting.final.view", "name": "View Final Drafting Output"},
    {"_id": "drafting.audit.view", "name": "View Drafting Audit Trail"},
    {"_id": "drafting.admin", "name": "Administer Drafting"},
    {"_id": "billing.plan.view", "name": "View Billing Plans"},
    {"_id": "billing.plan.manage", "name": "Manage Billing Plans"},
    {"_id": "subscription.entitlement.manage", "name": "Manage Subscription Entitlements"},
    {"_id": "subscription.usage.view", "name": "View Subscription Usage"},
    {"_id": "subscription.archive_access", "name": "Access Archive Subscription"},
    {"_id": "subscription.offboarding_export", "name": "Run Offboarding Export"},
]
