// Types matching the backend Pydantic models

export interface ApiError {
  detail?: string;
  message?: string;
}

export type PartyType = "Organization" | "Individual";

export type RepresentativeLevel = "organization" | "project";

export interface Representative {
  _id: string; // Matches the alias in Pydantic
  party_id: string; // Matches backend model field name
  name: string;
  email: string;
  contact_number?: string | null; // Matches backend model field name
  designation?: string | null; // Matches backend model field name
  is_primary: boolean; // Matches backend model field name
  level: RepresentativeLevel;
  use_head_office: boolean;
}

export interface Party {
  _id: string; // Matches the alias in Pydantic
  name: string;
  type: PartyType;
  organizationId?: string | null; // Matches alias
  contactEmail?: string | null; // Matches alias
  contactPhone?: string | null; // Matches alias
  createdAt: string; // Comes as string from JSON
  representatives: Representative[]; // Assuming embedded for now, adjust if fetched separately
  projects: string[];
  address?: string | null;
  city?: string | null;
  state?: string | null;
  pinCode?: string | null; // Matches alias
  country?: string | null;
}

export interface PartyListResponse {
  parties: Party[];
  total: number;
  page: number;
  limit: number;
  has_next: boolean;
  has_prev: boolean;
}

// Input type for creating a party (omitting fields generated by backend)
export type PartyCreateInput = Omit<
  Party,
  "_id" | "createdAt" | "representatives"
> & {
  // Explicitly define fields needed for creation payload
  name: string;
  type: PartyType;
  organizationId?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  projects: string[]; // Required by backend endpoint
  address?: string | null;
  city?: string | null;
  state?: string | null;
  pinCode?: string | null;
  country?: string | null;
};

// Input type for updating a party (all fields optional)
export type PartyUpdateInput = Partial<
  Omit<Party, "_id" | "createdAt" | "representatives">
>;

export interface Concern {
  _id: string; // Matches the alias in Pydantic
  name: string;
  email: string; // Backend model uses single email
  partyId: string; // Matches alias
  createdAt: string; // Comes as string from JSON
}

// Input type for creating a concern
export type ConcernCreateInput = Omit<Concern, "_id" | "createdAt">;

// Input type for updating a concern
export type ConcernUpdateInput = Partial<
  Omit<Concern, "_id" | "createdAt" | "partyId">
>;

// Input type for creating a representative
export type RepresentativeCreateInput = Omit<
  Representative,
  "_id" | "party_id"
>;

// Input type for updating a representative
export type RepresentativeUpdateInput = Partial<
  Omit<Representative, "_id" | "party_id">
>;

export interface Project {
  _id: string; // Matches alias
  name: string;
  organization_id: string;
  projectCode?: string;
  panNumber?: string;
  gstNumber?: string;
  address?: string;
  city?: string;
  state?: string;
  pinCode?: string;
  adminName?: string;
  adminEmail?: string;
  adminContact?: string;
  billingEnabled?: boolean;
  representatives?: Representative[];
  // Frontend display fields (not from backend)
  status?: "Active" | "Completed" | "On Hold";
  startDate?: string;
  letterCount?: number;
  teamSize?: number;
}

export interface Organization {
  _id: string;
  name: string;
  shortName?: string;
  panNumber?: string;
  gstNumber?: string;
  address?: string;
  city?: string;
  state?: string;
  pinCode?: string;
  adminName?: string;
  adminEmail?: string;
  adminContact?: string;
  billingEnabled?: boolean;
  representatives?: Representative[];
}

// Basic User structure expected from auth context/backend
// Adjust based on actual User model and auth implementation
export interface UserProfile {
  _id: string;
  email: string;
  full_name?: string;
  roles: Array<{ _id: string; name: string; permissions?: string[] }>; // Simplified Role structure
  organization_id?: string | null;
  project_ids?: string[] | null;
  is_active?: boolean;
  is_superuser?: boolean;
}

/**
 * Notification-related types used by NotificationCenter and Enhanced API
 */
export type NotificationCategory =
  | "drafting"
  | "approvals"
  | "uploads"
  | "comments";

export interface NotificationItem {
  id: string;
  type: string;
  created_at: string;
  unread: boolean;
  resource_type?: string;
  resource_id?: string;
  category?: NotificationCategory;
  data?: {
    title?: string;
    message?: string;
    document_id?: string;
    letter_no?: string;
    subject?: string | null;
    filename?: string;
    upload_type?: string;
    job_id?: string;
    successful_count?: number;
    failed_count?: number;
    organization_id?: string;
    project_id?: string;
    [key: string]: any;
  };
  [key: string]: any;
}

export interface NotificationListResponse {
  notifications: NotificationItem[];
  total: number;
  unread_count: number;
  has_more: boolean;
}
