/**
 * Gate 3 bullet 3: document upload, view, download, share, and authorization denial.
 *
 * SETUP     an owner session inside `E2E_STAGING_ORG_ID`, an outsider session in
 *           a different scope, and one disposable document whose letter number
 *           carries the run tag.
 * ACTION    upload it, read it back, download it, and repeat the read and the
 *           download as the outsider.
 * EXPECTED  owner: 200 and the bytes that were uploaded. Outsider: **403 or 404,
 *           never 200 and never an empty 200** - the matrix wording is "refused
 *           rather than shown an empty page", and an empty list with a 200 is
 *           the failure this bullet is looking for.
 * SECURITY  a 401 from a scoped endpoint is a FAILURE here, not a pass. The
 *           client turns 401 into a forced logout and 403 into a toast, so a
 *           scope refusal that arrives as 401 logs the user out of their own
 *           session; R-A8 recorded that exact masking and it was fixed.
 * CLEANUP   the document is deleted by id after being enumerated by run tag.
 *
 * The **share** leg is deliberately split. `POST /api/share-document`
 * (`routers/email_share.py:809`) authorises with
 * `Permissions.DOCUMENT_SHARE` and then sends real email through the configured
 * SMTP account. The authorisation half is deterministic and is asserted here.
 * The delivery half needs a staging SMTP sink, which is an owner decision about
 * staging configuration rather than a test to write, and until it is made this
 * bullet's row stays `EXECUTABLE_PARTIAL`. Asserting a click and calling it a
 * share would be the mocked-evidence failure in a different costume.
 *
 * NOT YET EXECUTED AGAINST A DEPLOYMENT. R-A8R has no staging window; the bullet
 * stays unchecked until a staging run produces the result.
 */
import { expect, test } from "@playwright/test";

import {
  RUN_TAG,
  cleanupRunOwned,
  ensureDisposableDocument,
  signIn,
} from "./fixtures";
import { requireStagingEnvironment } from "./staging-target";

const OWNER = ["E2E_STAGING_EMAIL", "E2E_STAGING_PASSWORD"] as const;
const OUTSIDER = ["E2E_OUTSIDER_EMAIL", "E2E_OUTSIDER_PASSWORD"] as const;
const SCOPE = ["E2E_STAGING_ORG_ID", "E2E_STAGING_PROJECT_ID"] as const;

/** What a scope refusal may be. 401 is excluded on purpose - see the header. */
const REFUSALS = [403, 404];

test.describe("Gate 3 bullet 3 - document lifecycle and authorization denial", () => {
  test.afterAll(async ({ playwright }) => {
    const context = await playwright.request.newContext();
    try {
      const session = await signIn(context, OWNER[0], OWNER[1]);
      const report = await cleanupRunOwned(session);
      expect(
        report.failed,
        `teardown left documents behind: ${JSON.stringify(report.failed)}`
      ).toEqual([]);
    } finally {
      await context.dispose();
    }
  });

  test("the owner uploads, views and downloads the document", async ({ request }) => {
    requireStagingEnvironment(...OWNER, ...SCOPE);
    const session = await signIn(request, OWNER[0], OWNER[1]);

    const document = await ensureDisposableDocument(session, "lifecycle");
    expect(document.letterNo).toContain(RUN_TAG);

    const view = await session.request.get(`/api/documents/${document.id}`);
    expect(view.status(), "the owner could not read their own document").toBe(200);
    const body = await view.json();
    expect(body.letterNo ?? body.letter_no).toBe(document.letterNo);

    const download = await session.request.get(`/api/documents/${document.id}/download`);
    expect(download.status(), "the owner could not download their own document").toBe(200);
    const bytes = await download.body();
    expect(bytes.byteLength, "the download returned no bytes").toBeGreaterThan(0);
    // The content is generated by the fixture, so this is an equality check and
    // not a "looks like a file" check.
    expect(bytes.toString("utf-8")).toContain(document.letterNo);
  });

  test("a user outside the document's scope is refused, not shown an empty page", async ({
    request,
    playwright,
  }) => {
    requireStagingEnvironment(...OWNER, ...OUTSIDER, ...SCOPE);
    const owner = await signIn(request, OWNER[0], OWNER[1]);
    const document = await ensureDisposableDocument(owner, "lifecycle");

    const outsiderContext = await playwright.request.newContext();
    try {
      const outsider = await signIn(outsiderContext, OUTSIDER[0], OUTSIDER[1]);

      const view = await outsider.request.get(`/api/documents/${document.id}`);
      expect(
        REFUSALS,
        `an out-of-scope read returned ${view.status()}; 200 is a leak and 401 is a ` +
          "scope refusal masked as an authentication failure, which logs the user out"
      ).toContain(view.status());

      const download = await outsider.request.get(`/api/documents/${document.id}/download`);
      expect(
        REFUSALS,
        `an out-of-scope download returned ${download.status()}`
      ).toContain(download.status());

      // The listing half. A refusal on the detail route means nothing if the
      // document is visible in the outsider's own list.
      const listing = await outsider.request.get("/api/documents", {
        params: { search: document.letterNo, limit: 50 },
      });
      expect(listing.status()).toBe(200);
      const rows: any[] = (await listing.json()).documents ?? [];
      expect(
        rows.map((row) => row?.letterNo ?? row?.letter_no),
        "the document is listed for a user outside its scope"
      ).not.toContain(document.letterNo);

      // The share leg's authorisation half. Delivery needs a staging SMTP sink
      // and is not asserted here; the refusal does not.
      const share = await outsider.request.post("/api/share-document", {
        headers: outsider.headers(),
        data: { document_id: document.id, to: ["nobody@example.invalid"] },
      });
      expect(
        [...REFUSALS, 422],
        `an out-of-scope share returned ${share.status()}`
      ).toContain(share.status());
    } finally {
      await outsiderContext.dispose();
    }
  });

  test("the owner sees the document in the browser", async ({ page, request }) => {
    const env = requireStagingEnvironment(...OWNER, ...SCOPE);
    const owner = await signIn(request, OWNER[0], OWNER[1]);
    const document = await ensureDisposableDocument(owner, "lifecycle");

    await page.goto("/login");
    await page.getByLabel("Work email").fill(env.E2E_STAGING_EMAIL);
    await page.getByLabel("Password", { exact: true }).fill(env.E2E_STAGING_PASSWORD);
    await Promise.all([
      page.waitForResponse(
        (response) => response.url().includes("/api/login") && response.request().method() === "POST"
      ),
      page.getByRole("button", { name: "Sign in" }).click(),
    ]);

    await page.goto(`/documents/${document.id}`);
    await expect(page.getByText(document.letterNo)).toBeVisible();
  });
});
