"""Contract Document Appraisal models (Contract Appraisal Report — v2 Phase 1).

A contract appraisal is generated by a thin orchestrator over the existing
citation-enforced contract-QA engine (``RetrievalService.contract_iterative_qa``),
one focused cited question per report section. Persistence is MongoDB/Motor with
Pydantic models aliased to ``_id`` (repo convention). Scope is
``(organization_id, project_id, document_ids[])`` — there is no first-class
contract_id entity in this repo; a "contract package" is a set of contract
``document_id``s under an (org, project).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class AppraisalJobStatus(str, Enum):
    QUEUED = "queued"
    RUNNING = "running"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ReportStatus(str, Enum):
    DRAFT = "draft"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    SUPERSEDED = "superseded"
    REJECTED = "rejected"


class CompletenessStatus(str, Enum):
    COMPLETE = "complete"
    INCOMPLETE = "incomplete"
    REQUIRES_REVIEW = "requires_review"


class ReportSection(BaseModel):
    """One generated report section with its own citations + support flag."""

    key: str
    title: str
    markdown: str = ""
    citations: List[Dict[str, Any]] = Field(default_factory=list)
    supported: bool = False  # had >=1 citation and was not "not found"
    confidence: float = 0.0


class AppraisalJob(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), alias="_id")
    organization_id: Optional[str] = None
    project_id: Optional[str] = None
    document_ids: List[str] = Field(default_factory=list)
    requested_by: Optional[str] = None
    status: AppraisalJobStatus = AppraisalJobStatus.QUEUED
    current_step: Optional[str] = None
    progress: int = 0
    error_message: Optional[str] = None
    report_id: Optional[str] = None
    ai_model_version: Optional[str] = None
    ai_prompt_version: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(populate_by_name=True)


class AppraisalReport(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), alias="_id")
    organization_id: Optional[str] = None
    project_id: Optional[str] = None
    job_id: Optional[str] = None
    document_ids: List[str] = Field(default_factory=list)
    report_version: int = 1
    status: ReportStatus = ReportStatus.DRAFT
    generated_by_ai: bool = True
    ai_model_version: Optional[str] = None
    ai_prompt_version: Optional[str] = None
    document_completeness_status: CompletenessStatus = CompletenessStatus.REQUIRES_REVIEW
    missing_documents: List[str] = Field(default_factory=list)
    executive_summary: str = ""
    full_report_markdown: str = ""
    sections: List[ReportSection] = Field(default_factory=list)
    structured_output: Dict[str, Any] = Field(default_factory=dict)
    citations: List[Dict[str, Any]] = Field(default_factory=list)
    overall_risk_rating: Optional[str] = None
    confidence_score: float = 0.0
    review_comments_count: int = 0
    reviewed_by: Optional[str] = None
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None
    is_locked: bool = False
    created_by: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(populate_by_name=True)


class ReviewComment(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), alias="_id")
    organization_id: Optional[str] = None
    project_id: Optional[str] = None
    report_id: str
    commented_by: Optional[str] = None
    comment_text: str
    section_reference: Optional[str] = None
    status: str = "open"  # open | resolved | rejected
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(populate_by_name=True)


# --- request / response bodies --------------------------------------------


class GenerateAppraisalRequest(BaseModel):
    organization_id: Optional[str] = None
    project_id: str = Field(..., min_length=1)
    document_ids: List[str] = Field(default_factory=list)


class ReportEditRequest(BaseModel):
    full_report_markdown: Optional[str] = None
    executive_summary: Optional[str] = None
    overall_risk_rating: Optional[str] = None


class DecisionRequest(BaseModel):
    comment: Optional[str] = None


class ReviewCommentRequest(BaseModel):
    comment_text: str = Field(..., min_length=1)
    section_reference: Optional[str] = None
