/** Generated by scripts/generate_permission_contract.py. Do not edit. */
export const PERMISSION_CONTRACT = {
  "canonical_permissions": [
    "billing.invoice.download",
    "billing.invoice.view",
    "billing.plan.manage",
    "billing.plan.view",
    "dms.admin",
    "dms.ai.contract_processing.run",
    "dms.arbitration.admin",
    "dms.arbitration.approve",
    "dms.arbitration.audit",
    "dms.arbitration.create",
    "dms.arbitration.edit",
    "dms.arbitration.export",
    "dms.arbitration.generate",
    "dms.arbitration.view",
    "dms.audit.view",
    "dms.bankguarantee.create",
    "dms.bankguarantee.delete",
    "dms.bankguarantee.edit",
    "dms.bankguarantee.export",
    "dms.bankguarantee.extend",
    "dms.bankguarantee.release",
    "dms.bankguarantee.view",
    "dms.chronology.admin",
    "dms.chronology.create",
    "dms.chronology.edit",
    "dms.chronology.export",
    "dms.chronology.verify",
    "dms.chronology.view",
    "dms.claim.assess",
    "dms.claim.create",
    "dms.claim.delete",
    "dms.claim.edit",
    "dms.claim.manage",
    "dms.claim.view",
    "dms.comment.add",
    "dms.concern.create",
    "dms.concern.delete",
    "dms.concern.edit",
    "dms.concern.view",
    "dms.contract.appraisal.approve",
    "dms.contract.appraisal.create_registers",
    "dms.contract.appraisal.edit",
    "dms.contract.appraisal.export",
    "dms.contract.appraisal.generate",
    "dms.contract.appraisal.reject",
    "dms.contract.appraisal.view",
    "dms.contract.clause.create",
    "dms.contract.clause.read",
    "dms.contract.master.manage",
    "dms.contract.master.view",
    "dms.contract.read",
    "dms.contract.timeline.view",
    "dms.contract.update",
    "dms.dashboard.view",
    "dms.document.bulk_download",
    "dms.document.delete",
    "dms.document.download",
    "dms.document.edit_metadata",
    "dms.document.link_reference",
    "dms.document.share",
    "dms.document.upload",
    "dms.document.view",
    "dms.evidence_graph.manage",
    "dms.evidence_graph.verify",
    "dms.evidence_graph.view",
    "dms.insurance.create",
    "dms.insurance.delete",
    "dms.insurance.edit",
    "dms.insurance.export",
    "dms.insurance.manage_types",
    "dms.insurance.view",
    "dms.ipc.approve",
    "dms.ipc.create",
    "dms.ipc.delete",
    "dms.ipc.edit",
    "dms.ipc.export",
    "dms.ipc.view",
    "dms.keydate.achievement",
    "dms.keydate.baseline.freeze",
    "dms.keydate.create",
    "dms.keydate.delete",
    "dms.keydate.edit",
    "dms.keydate.eot.determine",
    "dms.keydate.eot.freeze_determination",
    "dms.keydate.eot.lock_submission",
    "dms.keydate.eot.supersede",
    "dms.keydate.eot_approve",
    "dms.keydate.eot_submit",
    "dms.keydate.export",
    "dms.keydate.manage",
    "dms.keydate.view",
    "dms.organization.create",
    "dms.organization.delete",
    "dms.organization.edit",
    "dms.organization.view",
    "dms.project.manage",
    "dms.report.view",
    "dms.status.update",
    "dms.task.create",
    "dms.task.delete",
    "dms.task.edit",
    "dms.task.manage",
    "dms.task.view",
    "dms.user.manage",
    "dms.variation.approve",
    "dms.variation.create",
    "dms.variation.delete",
    "dms.variation.edit",
    "dms.variation.export",
    "dms.variation.view",
    "drafting.admin",
    "drafting.audit.view",
    "drafting.draft.create",
    "drafting.draft.edit",
    "drafting.draft.submit_for_review",
    "drafting.final.approve",
    "drafting.final.view",
    "drafting.request.accept",
    "drafting.request.assign",
    "drafting.request.create",
    "drafting.request.view",
    "drafting.review.approve",
    "drafting.review.perform",
    "drafting.review.return_for_revision",
    "drafting.workflow.cancel",
    "drafting.workflow.checkpoints",
    "drafting.workflow.force_v2",
    "drafting.workflow.resume",
    "drafting.workflow.state",
    "permissions:read",
    "roles:assign",
    "roles:create",
    "roles:delete",
    "roles:read",
    "roles:update",
    "settings.legal.manage",
    "settings.legal.view",
    "settings.notification.manage",
    "settings.notification.view",
    "settings.prompt.manage",
    "settings.prompt.view",
    "settings.smtp.manage",
    "settings.smtp.view",
    "settings.storage.manage",
    "settings.storage.view",
    "subscription.addon.manage",
    "subscription.archive_access",
    "subscription.cancel",
    "subscription.downgrade",
    "subscription.entitlement.manage",
    "subscription.history.view",
    "subscription.offboarding_export",
    "subscription.trial.manage",
    "subscription.upgrade",
    "subscription.usage.view"
  ],
  "permission_aliases": {
    "billing.invoice.download": [
      "organizations:read"
    ],
    "billing.invoice.view": [
      "organizations:read"
    ],
    "billing.plan.manage": [
      "system:admin"
    ],
    "billing.plan.view": [
      "organizations:read"
    ],
    "dms.admin": [
      "system:admin"
    ],
    "dms.arbitration.admin": [
      "projects:update"
    ],
    "dms.arbitration.approve": [
      "projects:update"
    ],
    "dms.audit.view": [
      "audit:read"
    ],
    "dms.bankguarantee.release": [
      "projects:update"
    ],
    "dms.chronology.admin": [
      "projects:update"
    ],
    "dms.claim.manage": [
      "projects:update"
    ],
    "dms.concern.create": [
      "concerns:create"
    ],
    "dms.concern.delete": [
      "concerns:delete"
    ],
    "dms.concern.edit": [
      "concerns:update"
    ],
    "dms.concern.view": [
      "concerns:read"
    ],
    "dms.contract.appraisal.approve": [
      "projects:update"
    ],
    "dms.contract.appraisal.reject": [
      "projects:update"
    ],
    "dms.contract.master.manage": [
      "projects:update"
    ],
    "dms.contract.master.view": [
      "projects:read"
    ],
    "dms.dashboard.view": [
      "projects:read"
    ],
    "dms.evidence_graph.manage": [
      "projects:update"
    ],
    "dms.ipc.approve": [
      "projects:update"
    ],
    "dms.keydate.baseline.freeze": [
      "projects:update"
    ],
    "dms.keydate.eot.determine": [
      "projects:update"
    ],
    "dms.keydate.eot.freeze_determination": [
      "projects:update"
    ],
    "dms.keydate.eot.lock_submission": [
      "projects:update"
    ],
    "dms.keydate.eot.supersede": [
      "projects:update"
    ],
    "dms.keydate.eot_approve": [
      "projects:update"
    ],
    "dms.keydate.manage": [
      "projects:update"
    ],
    "dms.organization.create": [
      "organizations:create",
      "orgs:create"
    ],
    "dms.organization.delete": [
      "organizations:delete",
      "orgs:delete"
    ],
    "dms.organization.edit": [
      "organizations:update",
      "orgs:edit"
    ],
    "dms.organization.view": [
      "organizations:read",
      "orgs:view"
    ],
    "dms.project.manage": [
      "projects:assign",
      "projects:create",
      "projects:delete",
      "projects:update"
    ],
    "dms.report.view": [
      "reports:view"
    ],
    "dms.task.manage": [
      "projects:update"
    ],
    "dms.user.manage": [
      "users:create",
      "users:delete",
      "users:read",
      "users:update"
    ],
    "dms.variation.approve": [
      "projects:update"
    ],
    "organizations:create": [
      "orgs:create"
    ],
    "organizations:delete": [
      "orgs:delete"
    ],
    "organizations:read": [
      "orgs:view"
    ],
    "organizations:update": [
      "orgs:edit"
    ],
    "projects:read": [
      "projects:view"
    ],
    "projects:update": [
      "projects:edit"
    ],
    "settings.legal.manage": [
      "settings:edit"
    ],
    "settings.legal.view": [
      "settings:view"
    ],
    "settings.notification.manage": [
      "settings:edit"
    ],
    "settings.notification.view": [
      "settings:view"
    ],
    "settings.prompt.manage": [
      "system:admin"
    ],
    "settings.prompt.view": [
      "system:admin"
    ],
    "settings.smtp.manage": [
      "settings:edit"
    ],
    "settings.smtp.view": [
      "settings:view"
    ],
    "settings.storage.manage": [
      "settings:edit"
    ],
    "settings.storage.view": [
      "settings:view"
    ],
    "subscription.addon.manage": [
      "system:admin"
    ],
    "subscription.archive_access": [],
    "subscription.cancel": [
      "system:admin"
    ],
    "subscription.downgrade": [
      "system:admin"
    ],
    "subscription.entitlement.manage": [
      "system:admin"
    ],
    "subscription.history.view": [
      "organizations:read"
    ],
    "subscription.offboarding_export": [],
    "subscription.trial.manage": [
      "system:admin"
    ],
    "subscription.upgrade": [
      "system:admin"
    ],
    "subscription.usage.view": [
      "reports:view"
    ]
  },
  "routes": {
    "/admin/billing-catalog": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "billing.plan.manage",
        "system:admin"
      ]
    },
    "/admin/legal-words": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "system:admin"
      ]
    },
    "/arbitration": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.view"
      ]
    },
    "/arbitration/cases": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.view"
      ]
    },
    "/arbitration/cases/new": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.create"
      ]
    },
    "/arbitration/claim": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.create"
      ]
    },
    "/arbitration/counterclaim": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.create"
      ]
    },
    "/arbitration/defence": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.create"
      ]
    },
    "/arbitration/drafts": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.view"
      ]
    },
    "/arbitration/rejoinder": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.arbitration",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.arbitration.create"
      ]
    },
    "/bank-guarantees": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.bank_guarantees",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.bankguarantee.view"
      ]
    },
    "/billing/return": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "billing.plan.view",
        "subscription.entitlement.manage",
        "subscription.upgrade"
      ]
    },
    "/chronology": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.chronology",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.chronology.view"
      ]
    },
    "/chronology/new": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.chronology",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.chronology.create"
      ]
    },
    "/claims": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.claims",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.claim.view"
      ]
    },
    "/concerns": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.concern.view"
      ]
    },
    "/contracts": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/contracts/appraisal": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.contract_appraisal",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.contract.appraisal.view"
      ]
    },
    "/contracts/clauses": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/contracts/master": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.contract_master",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.contract.master.view"
      ]
    },
    "/contracts/timeline": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.contract_timeline",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.contract.timeline.view"
      ]
    },
    "/contracts/viewer": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/dashboard": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.dashboard.view"
      ]
    },
    "/documents": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/documentsearch": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/documentviewer": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/email-groups": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "email_groups:read"
      ]
    },
    "/folders": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/health": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "system:admin"
      ]
    },
    "/insurance": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled",
        "feature.dms.insurance"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.insurance.view"
      ]
    },
    "/ipc-bills": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled",
        "feature.dms.ipc"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.ipc.view"
      ]
    },
    "/key-dates": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled",
        "feature.dms.key_dates"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.keydate.view"
      ]
    },
    "/legal-words": {
      "open_authenticated": true,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": []
    },
    "/letter-quality": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.drafting.enabled",
        "feature.drafting.requests"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "drafting.request.view"
      ]
    },
    "/letter-templates": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.drafting.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "letter_templates:read"
      ]
    },
    "/letters": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.drafting.enabled",
        "feature.drafting.requests"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "drafting.request.view"
      ]
    },
    "/notifications": {
      "open_authenticated": true,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": []
    },
    "/observability": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.report.view",
        "system:admin"
      ]
    },
    "/organizations": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.organization.view"
      ]
    },
    "/overview": {
      "open_authenticated": true,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": []
    },
    "/parties": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "parties:read"
      ]
    },
    "/permissions": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "roles:read",
        "permissions:read"
      ]
    },
    "/plan-settings": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "billing.plan.view",
        "subscription.entitlement.manage"
      ]
    },
    "/profile": {
      "open_authenticated": true,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "profile:read"
      ]
    },
    "/projects": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.dashboard.view"
      ]
    },
    "/reference": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/register": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.user.manage"
      ]
    },
    "/reports": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.report.view"
      ]
    },
    "/representatives": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "representatives:read"
      ]
    },
    "/retrieval-console": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.view"
      ]
    },
    "/security-terms": {
      "open_authenticated": true,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": []
    },
    "/settings": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "settings.storage.view",
        "settings.smtp.view",
        "settings.notification.view",
        "settings.legal.view",
        "settings.prompt.view"
      ]
    },
    "/share": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.share"
      ]
    },
    "/sla": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.claims",
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.claim.view"
      ]
    },
    "/subscription-management": {
      "open_authenticated": false,
      "required_all_features": [],
      "required_all_permissions": [],
      "required_any_permissions": [
        "billing.plan.view",
        "subscription.entitlement.manage",
        "subscription.upgrade"
      ]
    },
    "/tags": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "tags:read"
      ]
    },
    "/tasks": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled",
        "feature.dms.tasks"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.task.view"
      ]
    },
    "/upload": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.document.upload"
      ]
    },
    "/users": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.user.manage"
      ]
    },
    "/variations": {
      "open_authenticated": false,
      "required_all_features": [
        "feature.dms.enabled",
        "feature.dms.variations"
      ],
      "required_all_permissions": [],
      "required_any_permissions": [
        "dms.variation.view"
      ]
    }
  },
  "version": "2026-08-11.1"
} as const;

export const PERMISSION_CONTRACT_VERSION = PERMISSION_CONTRACT.version;
export const PERMISSION_ALIASES: Record<string, readonly string[]> = PERMISSION_CONTRACT.permission_aliases;
export const ROUTE_ACCESS_RULES = PERMISSION_CONTRACT.routes;
