from datetime import datetime

DEFAULT_ROLES = [
    {
        "_id": "superadmin",
        "name": "Super Admin",
        "is_system": True,
        "scope": "system",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "tags:create",
            "tags:update",
            "tags:delete",
            "projects:read",
            "users:read",
            "users:create",
            "users:update",
            "users:delete",
            "roles:read",
            "roles:create",
            "roles:update",
            "roles:delete",
            "permissions:read",
            "organizations:read",
            "parties:read",
            "parties:create",
            "parties:update",
            "parties:delete",
            "representatives:create",
            "representatives:update",
            "representatives:delete",
            "concerns:read",
            "concerns:create",
            "concerns:update",
            "concerns:delete",
        ],
    },
    {
        "_id": "orgadmin",
        "name": "Organization Admin",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "tags:create",
            "tags:update",
            "tags:delete",
            "projects:read",
            "users:read",
            "users:create",
            "users:update",
            "users:delete",
            "roles:read",
            "roles:create",
            "roles:update",
            "roles:delete",
            "permissions:read",
            "organizations:read",
            "organizations:create",
            "organizations:update",
            "organizations:delete",
            "parties:read",
            "parties:create",
            "parties:update",
            "parties:delete",
            "representatives:create",
            "representatives:update",
            "representatives:delete",
            "concerns:read",
            "concerns:create",
            "concerns:update",
            "concerns:delete",
        ],
    },
    {
        "_id": "orguser",
        "name": "Organization - User",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "projects:read",
            "users:read",
            "permissions:read",
            "organizations:read",
            "parties:read",
            "parties:update",
            "representatives:update",
            "concerns:read",
            "concerns:update",
        ],
    },
    {
        "_id": "contractmgr_org",
        "name": "Contract Manager - Organization",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "projects:read",
            "users:read",
            "permissions:read",
            "organizations:read",
            "parties:read",
            "parties:update",
            "representatives:update",
            "concerns:read",
            "concerns:update",
        ],
    },
    {
        "_id": "projectadmin",
        "name": "Project Admin",
        "is_system": True,
        "scope": "project",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "tags:create",
            "tags:update",
            "tags:delete",
            "projects:read",
            "users:read",
            "users:create",
            "users:update",
            "roles:read",
            "roles:create",
            "roles:update",
            "roles:assign",
            "permissions:read",
            "organizations:read",
            "parties:read",
            "concerns:read",
        ],
    },
    {
        "_id": "projectuser",
        "name": "Project - User",
        "is_system": True,
        "scope": "project",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:create",
            "documents:update",
            "documents:delete",
            "documents:approve",
            "documents:share",
            "documents:upload",
            "documents:comment",
            "tags:read",
            "projects:read",
            "users:read",
            "permissions:read",
            "organizations:read",
            "parties:read",
            "parties:update",
            "representatives:update",
            "concerns:read",
            "concerns:update",
        ],
    },
    {
        "_id": "doccontroller",
        "name": "Document Controller",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "documents:upload",
            "tags:read",
            "projects:read",
            "permissions:read",
        ],
    },
    {
        "_id": "reporter",
        "name": "Reporter",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "reports:view",
            "reports:create",
            "tags:read"
        ]
    },
    {
        "_id": "settings_manager",
        "name": "Settings Manager",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "settings:view",
            "settings:edit",
            "tags:read"
        ]
    },
    {
        "_id": "limited_user",
        "name": "Limited User",
        "is_system": True,
        "scope": "organization",
        "is_active": True,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "permissions": [
            "documents:read",
            "tags:read",
            "projects:read"
        ]
    }

]
