from ..core.security import get_password_hash

DEFAULT_USERS = [
    {
        "username": "superadmin",
        "email": "superadmin@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["superadmin"],
    },
    {
        "username": "orgadmin",
        "email": "orgadmin@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["orgadmin"],
        "organization_id": "org1",
        "projects": ["proj1"],
        "disabled": False,
    },
    {
        "username": "headcontract",
        "email": "headcontract@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["orguser"],
        "organization_id": "org1",
        "projects": ["proj1"],
        "disabled": False,
    },
    {
        "username": "contractmgr_org",
        "email": "contractmgr_org@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["orguser"],
        "organization_id": "org1",
        "projects": ["proj1"],
        "disabled": False,
    },
    {
        "username": "projectadmin",
        "email": "projectadmin@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["projectadmin"],
        "organization_id": "org2",
        "projects": ["proj2"],
        "disabled": False,
    },
    {
        "username": "contractmgr_proj",
        "email": "contractmgr_proj@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["projectuser"],
        "organization_id": "org2",
        "projects": ["proj2"],
        "disabled": False,
    },
    {
        "username": "doccontroller",
        "email": "doccontroller@example.com",
        "hashed_password": get_password_hash("password"),
        "roles": ["projectuser"],
        "organization_id": "org2",
        "projects": ["proj2"],
        "disabled": False,
    },
]
